name: Genealogy service publish
on:
  push:

env:
  image_name: genealogy
  HELM_CHART_REPOSITORY: femex
  VERSION: 0.0.1-${{ github.run_number }}

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reformat Branch name - replace
        uses: mad9000/actions-find-and-replace-string@2
        id: findandreplace
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '_'

      - name: Reformat Branch name - lowercase
        uses: ASzc/change-string-case-action@v2
        id: lowercase
        with:
          string: ${{ steps.findandreplace.outputs.value }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: femex/${{ env.image_name }}:${{env.VERSION}}

      - name: Package and publish helm
        run: |
          HELM_CHART_PATH="genealogy-helm-${{env.VERSION}}.tgz"
          echo "HELM_CHART_PATH: $HELM_CHART_PATH"
          sed -i -e "s/0.0.1-SNAPSHOT/${{env.VERSION}}/" helm/Chart.yaml
          sed -i -e "s/tag: .*/tag: ${{env.VERSION}}/" helm/values.yaml
          helm package helm
          helm push $HELM_CHART_PATH oci://registry-1.docker.io/${HELM_CHART_REPOSITORY}

